perl: Support newer Perl versions (e.g. v5.20.0)
There were error messages:

keys on reference is experimental at perl/printer.pm line 25.
Compilation failed in require at perl/step1_read_print.pl line 10.
BEGIN failed--compilation aborted at perl/step1_read_print.pl line 10.

---

Error: Modification of a read-only value attempted at perl/types.pm line 111, <FIN> line 1.